/* Auto-generated by scripts/sync-version.mjs. Do not edit manually. */
window.GBIT_VERSION = {
  "version": "0.9.0-demo.1",
  "major": 0,
  "minor": 9,
  "patch": 0,
  "stage": "demo",
  "build": 1,
  "buildDate": "2026-03-27",
  "cacheTag": "20260327a",
  "codename": "Mond Meadow Sprint"
}
