import fs from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, "..")
const versionJsonPath = path.join(projectRoot, "version.json")
const versionJsPath = path.join(projectRoot, "version.js")

const raw = await fs.readFile(versionJsonPath, "utf8")
const info = JSON.parse(raw)

const payload = {
  version: info.version,
  major: info.major,
  minor: info.minor,
  patch: info.patch,
  stage: info.stage,
  build: info.build,
  buildDate: info.buildDate,
  cacheTag: info.cacheTag,
  codename: info.codename,
}

const content = `/* Auto-generated by scripts/sync-version.mjs. Do not edit manually. */
window.GBIT_VERSION = ${JSON.stringify(payload, null, 2)}
`

await fs.writeFile(versionJsPath, content, "utf8")
console.log(`VERSION_SYNCED ${payload.version} (${payload.cacheTag}) -> ${path.relative(projectRoot, versionJsPath)}`)
